### ISSUE TITLE
Design Hausl-Page

### ISSUE THREAD

**Issue by sanada089** [sanada089/HTML-Tool-4-School#11]

**Comment by Leniiiiiii** [comment]
Aufgabenstellung 1

**Comment by sanada089** [comment]
In den jeweiligen Hausl-Pages soll der Weg zur Hilfe beschrieben werden.
z.B. Fragezeichenbutton -> Grundgerüst o.Ä.

**Comment by Leniiiiiii** [comment]
Hab versucht, die Überschriften, nach den Buttons zu benennen... 

1. entweder beim Start-Popup so erklären
2. oder noch den Weg beschreiben, bzw. Bild vom Button einfügen
