### ISSUE TITLE
Inhalt Gscheidhaferl-Page

### ISSUE THREAD

**Issue by sanada089** [sanada089/HTML-Tool-4-School#12]

**Comment by sanada089** [comment]
Sinnvolle Hilfeoptionen finden und in Buttons füllen

**Comment by Leniiiiiii** [comment]
Bis auf Design fertig - da fehlen im vorherigen Schritt noch die passenden Blöcke

**Comment by Leniiiiiii** [comment]
Schließe ich mal - gibt anderes Issue
