### ISSUE TITLE
Gscheidhaferl- und Hauslzeichnungen

### ISSUE THREAD

**Issue by sanada089** [sanada089/HTML-Tool-4-School#20]

**Comment by Leniiiiiii** [comment]
Hab schon ein paar Leute gefragt, aber noch keine positiven Rückmeldungen...

**Comment by Leniiiiiii** [comment]
Würde die vorhandenen verwenden und Quellen angeben?!

**Comment by sanada089** [comment]
Hab mal die KI befragt und das ist was sie ausgegeben hat
