### ISSUE TITLE
Titel-Block sollte im Head voreingefügt sein und in den Body nicht einfügbar

### ISSUE THREAD

**Issue by sanada089** [sanada089/HTML-Tool-4-School#23]

**Comment by Leniiiiiii** [comment]
Titel kann jetzt nur im Kopf eingefügt werden - braucht danach einen Text

**Comment by sanada089** [comment]
Headblock nochmal überarbeiten. Titel und Rest unterschiedliche Lücken

**Comment by sanada089** [comment]
Ist jetzt wie es soll hoffentlich
