### ISSUE TITLE
Lena kann nicht zu Gscheidhaferl wechseln und anschließend Code anzeigen lassen

### ISSUE THREAD

**Issue by sanada089** [sanada089/HTML-Tool-4-School#28]

**Comment by Leniiiiiii** [comment]
![Screenshot (1779)](https://user-images.githubusercontent.com/106515780/205626857-28996d18-43a2-4a0d-a956-317530d8dd31.png)

**Comment by sanada089** [comment]
https://stackoverflow.com/questions/25098021/securityerror-blocked-a-frame-with-origin-from-accessing-a-cross-origin-frame
