### ISSUE TITLE
Specialtextblock sinnvoll machen

### ISSUE THREAD

**Issue by sanada089** [sanada089/HTML-Tool-4-School#34]
Schriftfarbe raus, dafür unterstrichen, fett, kursiv.... rein. Schriftart raus.

**Comment by sanada089** [comment]
Soll am Ende:
Schriftfarbe,
Schriftgröße,
{Unterstrichen,
fett,
kursiv} als Dropdown

**Comment by Leniiiiiii** [comment]
ist glaube ich soweit fertig
