### ISSUE TITLE
> Startzustand

### ISSUE THREAD

**Issue by sanada089** [sanada089/HTML-Tool-4-School#41]
> Startzustand: Macht es Sinn den vorzugeben? Vorteil: keine Fehler können übernommen werden Nachteil: Individualisierung geht verloren

Startzustand wird nicht vorgegeben. Button zum Startzustand laden wird eingefügt.
Muss im Startpopup noch erklärt werden

_Originally posted by @sanada089 in https://github.com/sanada089/HTML-Tool-4-School/issues/39#issuecomment-1362604476_

**Comment by sanada089** [comment]
Button fehlt. function() ist da

**Comment by Leniiiiiii** [comment]
Button ist eingefügt

**Comment by Leniiiiiii** [comment]
Für Level 15 noch einfügen
