### ISSUE TITLE
Hintergrund am Rand absichtlich wieder weiß?

### ISSUE THREAD

**Issue by sanada089** [sanada089/HTML-Tool-4-School#44]
Hintergrund am Rand absichtlich wieder weiß?

_Originally posted by @Leniiiiiii in https://github.com/sanada089/HTML-Tool-4-School/issues/39#issuecomment-1362041972_

**Comment by sanada089** [comment]
hast du schon gefixt?

**Comment by Leniiiiiii** [comment]
schon erledigt!
