### ISSUE TITLE
Gscheidhaferl-Page

### ISSUE THREAD

**Issue by sanada089** [sanada089/HTML-Tool-4-School#5]
HTML-Seite erstellen, die Hilfe-Buttons zur jeweiligen Aufgabe und einen Zurück-Button bietet.

**Comment by sanada089** [comment]
Braucht noch Buttons die etwas machen, sieht aber schon brauchbar aus.

**Comment by sanada089** [comment]
Buttonfunktionalität erstellen

**Comment by sanada089** [comment]
Buttons funktionieren. Hilfeoptionen müssen noch sinnvoll befüllt werden.

**Comment by sanada089** [comment]
Button und sprechblasenbreite überprüfen

**Comment by sanada089** [comment]
Muss nochmal angeschaut werden auf Lenas PC. Bei mir funktioniert es Stand jetzt

**Comment by sanada089** [comment]
Buttons werden untereinander angezeigt. iFrame rutscht nach rechts.

**Comment by Leniiiiiii** [comment]
Text raus, iframe hoch

**Comment by sanada089** [comment]
Text ist raus. Iframe ist hoch

**Comment by sanada089** [comment]
Nochmal anpassen, so dass es auch bei Lena okay aussieht

**Comment by Leniiiiiii** [comment]
Hab den Aufbau nochmal geändert

**Comment by sanada089** [comment]
Sollte jetzt final funktionieren. Evtl. Buttonposition in spätem Schritt noch einmal überarbeiten
