### ISSUE TITLE
Popup

### ISSUE THREAD

**Issue by Leniiiiiii** [sanada089/HTML-Tool-4-School#50]
beim Popup eventuell Hausl und Gscheidhaferl mit Bild vorstellen?! 
"Wir begleiten dich durchs Spiel"

**Comment by sanada089** [comment]
Benötigt Bilder in besserer Qualität.

Leniiiiiii ***@***.***> schrieb am Fr., 30. Dez. 2022, 15:27:

**Comment by sanada089** [comment]
Hausl und Gscheidhaferl vorstellen. Generelle Aufgabe umreißen

**Comment by sanada089** [comment]
Hast du schon fertig gemacht, oder?

**Comment by sanada089** [comment]
Rechtsklick -> kopieren

**Comment by Leniiiiiii** [comment]
Texte sind soweit fertig
