### ISSUE TITLE
Hilfestellungen überarbeiten

### ISSUE THREAD

**Issue by sanada089** [sanada089/HTML-Tool-4-School#63]
Schriftart, Überschrift, Screenshots

**Comment by Leniiiiiii** [comment]
Es fehlt noch eine Erklärung für das Einfügen von Bildern

**Comment by Leniiiiiii** [comment]
Tabelle: muss noch überarbeitet werden, sobald die Blöcke richtig funktionieren

**Comment by Leniiiiiii** [comment]
Alle anderen soweit angepasst!

**Comment by Leniiiiiii** [comment]
Textstruktur ist etwas viel Text und Info - Problem für SuS?

**Comment by Leniiiiiii** [comment]
Alle Hilfeseiten überarbeitet!
