### ISSUE TITLE
Inhalt für die verschiedenen Level (Hausl-Pages)

### ISSUE THREAD

**Issue by sanada089** [sanada089/HTML-Tool-4-School#7]

**Comment by sanada089** [comment]
Aufgabenstellung am besten für gesamte Level mit Unterteilung.

**Comment by Leniiiiiii** [comment]
Hab alles soweit auf Papier ausgearbeitet; muss es noch übertragen und schülergerechte formulieren

**Comment by Leniiiiiii** [comment]
Bleibt die Tabellenfrage: Ist ein kompletter Stundenplan sinnvoll? oder werden es zu viele Blöcke?! - allerdings ist es eine der letzten Aufgaben, da könnte es ja mal schwieriger werden...

**Comment by Leniiiiiii** [comment]
Alle Aufgaben ausformuliert, bis auf die Tabellenaufgabe

**Comment by Leniiiiiii** [comment]
[Aufgabenstellung.docx](https://github.com/sanada089/HTML-Tool-4-School/files/10365865/Aufgabenstellung.docx)

**Comment by Leniiiiiii** [comment]
[Aufgabenstellung.docx](https://github.com/sanada089/HTML-Tool-4-School/files/10366414/Aufgabenstellung.docx)

**Comment by Leniiiiiii** [comment]
Alle Aufgaben soweit ausformuliert
Aktuelle Aufgabenstellungen:
[Aufgabenstellung.docx](https://github.com/sanada089/HTML-Tool-4-School/files/10366705/Aufgabenstellung.docx)

**Comment by Leniiiiiii** [comment]
Eventuell noch eine Aufgabe mit dem Block "Bilderlink" einfügen!
