### ISSUE TITLE
Design für die Mainpage

### ISSUE THREAD

**Issue by sanada089** [sanada089/HTML-Tool-4-School#8]

**Comment by Leniiiiiii** [comment]
Design geändert (Aufbau der Seite, Buttons einheitlich, Farbe)

**Comment by sanada089** [comment]
Vorerst Design gefunden. Evtl. nochmal Farbwechsel

**Comment by Leniiiiiii** [comment]
Seitenaufbau ändern

**Comment by Leniiiiiii** [comment]
Oberbegriffe umbenennen

**Comment by Leniiiiiii** [comment]
Farbgestaltung Blöcke

**Comment by sanada089** [comment]
Den RIESENFehler der unterschiedlichen Höhen beheben (so absolut unbenutzbar)
