### ISSUE TITLE
Popupbuttons an Seitenstil anpassen

### ISSUE THREAD

**Issue by sanada089** [sanada089/HTML-Tool-4-School#95]

**Comment by Leniiiiiii** [comment]
im letzten Popup evtl. einen Button Start (der dann das Popup schließt und Aufgabe 1 angezeigt wird)

**Comment by Leniiiiiii** [comment]
Popup an Design angepasst

**Comment by Leniiiiiii** [comment]
Start Button eingefügt (auf allen Seiten)

**Comment by Leniiiiiii** [comment]
FEHLT: Button nur beim letzten Popup
